name: 'Markdown Docs'
author: ldeluigi
description: ''
inputs:
  mode:
    description: 'Can be "Markdown" or "md" to generate GitHub compliant markdown files or "HTML" or "gh-pages" to generate a static website'
    required: true
    default: 'HTML'
  src:
    description: 'Source path'
    required: true
    default: '.'
  dst:
    description: 'Output path'
    required: true
    default: 'docs'
runs:
  using: 'docker'
  image: 'deloo/markdown-docs'
  args:
    - ${{ inputs.mode }}
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
