name: 'Markdown Docs'
author: ldeluigi
description: 'Generates a documentation website from Markdown files with many extensions: https://github.com/ldeluigi/markdown-docs#readme'
branding:
  icon: 'file-text'
  color: 'gray-dark'
inputs:
  src:
    description: >
      Source path.
      Default: .
    required: true
    default: '.'
  dst:
    description: >
      Output path.
      Default: docs
    required: true
    default: 'docs'
  language:
    description: >
      Language selector for mkdocs search feature and more.
      Default: en
    required: false
    default: 'en'
  icon:
    description: >
      One of https://materialdesignicons.com icons.
      Displayed at the top left, links to the home.
      Default: library
    required: false
    default: 'library'
  primary-color:
    description: >
      One of red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green,
      light green, lime, yellow, amber, orange, deep orange.
      Default: indigo
    required: false
    default: indigo
  secondary-color:
    description: >
      One of red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green,
      lime, yellow, amber, orange, deep orange.
      Default: indigo
    required: false
    default: indigo
  hide-repository:
    description: >
      If set to true, will generate a website that doesn't link back to the repository on GitHub. Defaults to false.
    required: false
    default: 'false'
  title:
    description: >
      The title for the documentation website. Defaults to the name of the repository.
    required: false
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'docker://deloo/markdown-docs:0.6.5'
  env:
    TITLE: ${{ inputs.title }}
    LANGUAGE: ${{ inputs.language }}
    ICON: ${{ inputs.icon }}
    PRIMARY_COLOR: ${{ inputs.primary-color }}
    SECONDARY_COLOR: ${{ inputs.secondary-color }}
    HIDE_REPOSITORY: ${{ inputs.hide-repository }}
  args:
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
