name: 'Markdown Docs'
author: ldeluigi
description: 'Generates file based on documentation written in Markdown (with many extensions, see https://github.com/ldeluigi/markdown-docs#readme) based on MkDocs and Python Markdown'
branding:
  icon: 'file-text'
  color: 'gray-dark'
inputs:
  src:
    description: 'Source path'
    required: true
    default: '.'
  dst:
    description: 'Output path'
    required: true
    default: 'docs'
runs:
  using: 'docker'
  image: 'docker://deloo/markdown-docs'
  args:
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
